name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "name=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            a38-kanban-backend:${{ steps.date.outputs.date }}
            a38-kanban-backend:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
