name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set date tag in env
        run: echo "date_tag=$(date +%Y%m%d-%H%M)" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag rlanyi/a38-kanban-backend:$date_tag --tag rlanyi/a38-kanban-backend:latest

      - name: Push the Docker image
        run: docker push rlanyi/a38-kanban-backend:$date_tag && docker push rlanyi/a38-kanban-backend:latest
